#!/usr/bin/env python

import os
import sys
import socket
import select
import struct
import json
import time
import uuid
import ConfigParser

config = ConfigParser.ConfigParser()
config.read( 'client.conf' )


message = {
	'id':		uuid.uuid4().hex,
	'pid':		os.getpid(),
	'client_id':	uuid.uuid4().hex,
	'auth':		uuid.uuid4().hex,
	'command':	'stat',
	'argument':	'udp_client'
}

network_address	= config.get( 'client', 'network_address' )
network_port	= config.getint( 'client', 'network_port' )
status_timeout	= config.getfloat( 'client', 'status_timeout' )
data_timeout	= config.getfloat( 'client', 'data_timeout' )
buffer_size	= config.getint( 'client', 'buffer_size' )

cmd = sys.argv[1]
cmd_arg = sys.argv[2]

if not cmd is None:
	message['command'] = cmd
	message['argument'] = cmd_arg

s = socket.socket( socket.AF_INET, socket.SOCK_DGRAM )


ttl = struct.pack( 'b', 1 )
s.setsockopt( socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, ttl )

sent = s.sendto( json.dumps(message), ( network_address, network_port ) )
s.settimeout( status_timeout )
start = time.time()

while 1:
	try:
		msg_in, sender_addr = s.recvfrom( buffer_size )
	except socket.timeout, ex:
		print >> sys.stderr, "socket.timeout %s" % ex
		break
	else:
		print "after %.5f msg_in='%s'\n" % ( (time.time() - start), msg_in )
		response = json.loads(msg_in)
		s.settimeout( data_timeout )
		s.sendto( json.dumps(message), ( response['host'][0], response['host'][1] ) )
s.close()
sys.exit(0)

