#!/usr/bin/env python

import os
import sys
import socket
import struct
import json
import hashlib
import ConfigParser

config = ConfigParser.ConfigParser()
config.read( 'server.conf' )

buffer_size	= config.getint( 'general', 'buffer_size' )

data_address	= config.get( 'data', 'network_address' )
data_port	= config.getint( 'data', 'network_port' )

s = socket.socket( socket.AF_INET, socket.SOCK_DGRAM )
s.bind( ( data_address, data_port) )

while 1:
	msg_in, remote_addr = s.recvfrom( buffer_size )

	print "received='%s' from '%s'" % ( msg_in, remote_addr )


s.close()
sys.exit(0)
