#!/usr/bin/env python

import os
import sys
import socket
import select
import struct
import json

message = {}
message['msg'] = "from client"
message['pid'] = os.getpid()

network_address = sys.argv[1]
network_port = int(sys.argv[2])

s = socket.socket( socket.AF_INET, socket.SOCK_DGRAM )

s.settimeout( 0.2 )

ttl = struct.pack( 'b', 1 )
s.setsockopt( socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, ttl )

sent = s.sendto( json.dumps(message), ( network_address, network_port ) )
print >> sys.stderr, "sent='%s'" % sent
r_s, _, _ = select.select( [ s ], [], [] )
for r in r_s:
	msg_in, sender_addr = r.recvfrom(512)
	print "msg_in='%s'\n" % msg_in
s.close()
sys.exit(0)

